# Generated by Django 4.0.3 on 2022-04-13 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='created_at',
            new_name='create_at',
        ),
    ]
